### PR TITLE
Added default and class value settings. Any interest?

### PR DESCRIPTION
**Pull request by synchronizing**
I needed these modifications for my own projects, and figured I would open a PR to ask if this is something that you guys might want to add to the project (I fully understand if not as it is a very niche setting). In short, two flags have been added:

### `keep_default_values` (defaults to `True`)

Default values are kept in the documentation. If set to ``False`` default values are not shown.

#### `True`
Screen Shot 2021-11-06 at 8 42 58 PM

#### `False`
Screen Shot 2021-11-06 at 8 43 13 PM

### `hide_class_values` (defaults to `False`)

If set to ``True`` ``__init__`` values are hidden in the class directive. ``Class(value):`` becomes ``Class:``.

#### `True`
Screen Shot 2021-11-06 at 8 42 58 PM

#### `False`

Screen Shot 2021-11-06 at 8 44 09 PM

This PR is missing tests to go along with it. Also, as I write this PR I've noticed that keeping counter opposite flags (`keep` and `hide`) is a bit redundant - I can also change this.

### CODE REVIEW

**Comment by agronholm** [comment]
There is interested in further developing sphinx-autodoc-typehints but I currently have no capacity to work on the project. I've started recruiting a new maintainer some time ago but nobody has been willing to go through with it yet.

**Comment by gaborbernat** [comment]
> There is interested in further developing sphinx-autodoc-typehints but I currently have no capacity to work on the project. I've started recruiting a new maintainer some time ago but nobody has been willing to go through with it yet.

I'm happy to pick this up if you're ok with that.

**Comment by agronholm** [comment]
> > There is interested in further developing sphinx-autodoc-typehints but I currently have no capacity to work on the project. I've started recruiting a new maintainer some time ago but nobody has been willing to go through with it yet.
> 
> I'm happy to pick this up if you're ok with that.

That would be awesome. I've sent you an invite.

**Comment by gaborbernat** [comment]
> That would be awesome. I've sent you an invite.

Thanks, sent you an e-mail to clarify some further details :+1:

**Comment by gaborbernat** [comment]
@synchronizing I've rebased on main, can you please fix the CI, thanks!

**Comment by synchronizing** [comment]
> @synchronizing I've rebased on main, can you please fix the CI, thanks!

Happy New Years! Will see if I get to it some point this week, thanks.

**Comment by synchronizing** [comment]
@gaborbernat is there interest on this PR? Any thoughts on naming?

**Comment by gaborbernat** [comment]
Is awaiting for someone to finish it and pass the CI.

**Comment by synchronizing** [comment]
Before I put the effort to fix the CI I think it would be worth to understand if this is a feature that you would like to add - otherwise I rather just close the PR. Lmk!

**Comment by gaborbernat** [comment]
I'd definitely accept this PR, behind feature flags.

**Comment by gaborbernat** [comment]
@synchronizing I'll close this PR but feel free to re-open it once you get to work on it.

**Pull request closed without merging**
