### PR TITLE
Fixed default options not displaying for parameters without type hints.

### LINKED ISSUE #234: `typehints_defaults` does not work when missing python3 sytle type hints
Given function signature 
```python
def grid_archive_heatmap(archive, ax=None, ... )
```
and setting `typehints_defaults = "comma" ("braces", "braces-after")` . `sphinx-autodoc-typehints` does not correctly add a "default=" clause for the argument `ax` in the documentation.

This problem was encountered at https://github.com/icaros-usc/pyribs/pull/204.

### PR DESCRIPTION
**Pull request by BhavyeMathur**
Resolves #234

`format_default()` takes a new parameter `is_annotated` to better format the option.

`_inject_types_to_docstring()` now iterates through all signature parameters. Unchanged behaviour for parameters with type hints, but parameters without type hints now get their default value shown.

Also added tests with 4 functions trying out different variations with/without type hints, default values, and return types.

Works with both the "braces" and "commas" setting for `typehints_defaults`.

Before:
image

After:
image

### CODE REVIEW

**Review by gaborbernat — APPROVED** [review]

**Comment by gaborbernat** [comment]
Looks alright once the CI passes.

**Comment by BhavyeMathur** [comment]
Any ideas on how to fix this?

`tests/test_sphinx_autodoc_typehints.py:1131: error: "Config" has no attribute "typehints_defaults"`

```python
set_python_path()
app.config.master_doc = "without_complete_typehints"  # type: ignore # create flag
app.config.typehints_defaults = "comma"
app.build()
```

A similar syntax seems to work with the tests above this one...

**Comment by gaborbernat** [comment]
You must add trailing `# type: ignore` on the line.

**Comment by BhavyeMathur** [comment]
@gaborbernat does this look okay?

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
